// <auto-generated />
using System;
using System.Numerics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace warfront_legacy_web_api_core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241215111714_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Flag", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("Userid")
                        .HasColumnType("integer");

                    b.Property<string>("flagName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("imgURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isFree")
                        .HasColumnType("boolean");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("Userid");

                    b.ToTable("Flags");
                });

            modelBuilder.Entity("Session", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("loserid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("sessionDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("winnerid")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("loserid");

                    b.HasIndex("winnerid");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("birthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<BigInteger>("expCount")
                        .HasColumnType("numeric");

                    b.Property<string>("passHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("registrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("usernameHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WarriorUnit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("Userid")
                        .HasColumnType("integer");

                    b.Property<bool>("isFree")
                        .HasColumnType("boolean");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<string>("warrioirUnitSkinName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("warriorUnitSkinURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("Userid");

                    b.ToTable("WarriorUnits");
                });

            modelBuilder.Entity("Flag", b =>
                {
                    b.HasOne("User", null)
                        .WithMany("flagAttribute")
                        .HasForeignKey("Userid");
                });

            modelBuilder.Entity("Session", b =>
                {
                    b.HasOne("User", "loser")
                        .WithMany()
                        .HasForeignKey("loserid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "winner")
                        .WithMany()
                        .HasForeignKey("winnerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("loser");

                    b.Navigation("winner");
                });

            modelBuilder.Entity("WarriorUnit", b =>
                {
                    b.HasOne("User", null)
                        .WithMany("warriorUnitAttribute")
                        .HasForeignKey("Userid");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("flagAttribute");

                    b.Navigation("warriorUnitAttribute");
                });
#pragma warning restore 612, 618
        }
    }
}
