// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace warfront_legacy_web_api_core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BuilderUnit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("PlayerInformationid")
                        .HasColumnType("integer");

                    b.Property<string>("bldUnitSkinName")
                        .HasColumnType("text");

                    b.Property<string>("bldUnitSkinURL")
                        .HasColumnType("text");

                    b.Property<bool>("isFree")
                        .HasColumnType("boolean");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("PlayerInformationid");

                    b.ToTable("bldUnits");
                });

            modelBuilder.Entity("EngineerUnit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("PlayerInformationid")
                        .HasColumnType("integer");

                    b.Property<string>("engUnitSkinName")
                        .HasColumnType("text");

                    b.Property<string>("engUnitSkinURL")
                        .HasColumnType("text");

                    b.Property<bool>("isFree")
                        .HasColumnType("boolean");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("PlayerInformationid");

                    b.ToTable("engUnits");
                });

            modelBuilder.Entity("Flag", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("PlayerInformationid")
                        .HasColumnType("integer");

                    b.Property<string>("flagName")
                        .HasColumnType("text");

                    b.Property<string>("imgURL")
                        .HasColumnType("text");

                    b.Property<bool>("isFree")
                        .HasColumnType("boolean");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("PlayerInformationid");

                    b.ToTable("Flags");
                });

            modelBuilder.Entity("PlayerInformation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("birthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<int>("expCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("registrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("userName")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("PlayerInf");
                });

            modelBuilder.Entity("Session", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("loserid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("sessionDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("winnerid")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("loserid");

                    b.HasIndex("winnerid");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("SniperUnit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("PlayerInformationid")
                        .HasColumnType("integer");

                    b.Property<bool>("isFree")
                        .HasColumnType("boolean");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<string>("sniperUnitSkinName")
                        .HasColumnType("text");

                    b.Property<string>("sniperUnitSkinURL")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("PlayerInformationid");

                    b.ToTable("SniperUnits");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("passHash")
                        .HasColumnType("text");

                    b.Property<int?>("playerInformationid")
                        .HasColumnType("integer");

                    b.Property<string>("usernameHash")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("playerInformationid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WarriorUnit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("PlayerInformationid")
                        .HasColumnType("integer");

                    b.Property<bool>("isFree")
                        .HasColumnType("boolean");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<string>("warrioirUnitSkinName")
                        .HasColumnType("text");

                    b.Property<string>("warriorUnitSkinURL")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("PlayerInformationid");

                    b.ToTable("WarriorUnits");
                });

            modelBuilder.Entity("BuilderUnit", b =>
                {
                    b.HasOne("PlayerInformation", null)
                        .WithMany("bldUnitAttribute")
                        .HasForeignKey("PlayerInformationid");
                });

            modelBuilder.Entity("EngineerUnit", b =>
                {
                    b.HasOne("PlayerInformation", null)
                        .WithMany("engUnitAttribute")
                        .HasForeignKey("PlayerInformationid");
                });

            modelBuilder.Entity("Flag", b =>
                {
                    b.HasOne("PlayerInformation", null)
                        .WithMany("flagAttribute")
                        .HasForeignKey("PlayerInformationid");
                });

            modelBuilder.Entity("Session", b =>
                {
                    b.HasOne("PlayerInformation", "loser")
                        .WithMany()
                        .HasForeignKey("loserid");

                    b.HasOne("PlayerInformation", "winner")
                        .WithMany()
                        .HasForeignKey("winnerid");

                    b.Navigation("loser");

                    b.Navigation("winner");
                });

            modelBuilder.Entity("SniperUnit", b =>
                {
                    b.HasOne("PlayerInformation", null)
                        .WithMany("SniperUnitAttribute")
                        .HasForeignKey("PlayerInformationid");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.HasOne("PlayerInformation", "playerInformation")
                        .WithMany()
                        .HasForeignKey("playerInformationid");

                    b.Navigation("playerInformation");
                });

            modelBuilder.Entity("WarriorUnit", b =>
                {
                    b.HasOne("PlayerInformation", null)
                        .WithMany("warriorUnitAttribute")
                        .HasForeignKey("PlayerInformationid");
                });

            modelBuilder.Entity("PlayerInformation", b =>
                {
                    b.Navigation("SniperUnitAttribute");

                    b.Navigation("bldUnitAttribute");

                    b.Navigation("engUnitAttribute");

                    b.Navigation("flagAttribute");

                    b.Navigation("warriorUnitAttribute");
                });
#pragma warning restore 612, 618
        }
    }
}
